### ISSUE TITLE
YAML base

### ISSUE THREAD

**Issue by ygkn** [lit-kansai-members/music#66]

**Comment by ygkn** [comment]
```yaml
- year: 2016
  camps:
  - name: "Xmas Camp 2016"
    background: "./path/to/background.png"
    songs:
    - title: "SEKAI NO OWARI - Hey Ho"
    - description: |
      [YouTube](//youtu.be/qfsr0S_QGOU)
      [歌詞(J-Lyric.net)](http://j-lyric.net/artist/a055790/l03c659.html)
```

@KawakawaRitsuki 

こんな感じ？
